### ISSUE TITLE
Type error not capturing and some other error not capturing. 

### ISSUE THREAD

**Issue by minhaj57sorder** [ashra-tech/ashra-log#9]
Here are screenshot.
And also need to get triggered the variable like state changes in react if the log get updated.
<img width="1440" alt="Screenshot 2024-07-09 at 3 22 19 PM" src="https://github.com/ashra-tech/ashra-log/assets/74466041/0641f59f-975e-4453-8402-31da491b8ef6">
<img width="1432" alt="Screenshot 2024-07-09 at 3 24 58 PM" src="https://github.com/ashra-tech/ashra-log/assets/74466041/3ea32ba3-47b9-4344-b237-0df7a4287fa4">

**Comment by devlopersabbir** [comment]
@minhaj57sorder issue #11 fixed
